server:
  port: 8081

spring:
  application:
    name: demo

  data:
    mongodb:
      database: demo-api-db
      host: localhost
      auto-index-creation: true
      port: 27017

  devtools:
    add-properties: true

management:
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include:
          - prometheus
          - health
          - info
          - metrics
          - env
          - shutdown
          - startup
